# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import pygravitino
from pygravitino.model.identity_partitioning import IdentityPartitioning
from pygravitino import configuration


class TestIdentityPartitioning(unittest.TestCase):
    """IdentityPartitioning unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
