# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import pygravitino
from pygravitino.dto.requests.add_partitions_request_dto import AddPartitionsRequestDto
from pygravitino import configuration


class TestAddPartitionsRequestDto(unittest.TestCase):
    """AddPartitionsRequestDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
