# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pygravitino import schemas  # noqa: F401


class CatalogUpdatesRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "updates",
        }
        
        class properties:
            
            
            class updates(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['CatalogUpdateRequest']:
                        return CatalogUpdateRequest
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['CatalogUpdateRequest'], typing.List['CatalogUpdateRequest']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'updates':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'CatalogUpdateRequest':
                    return super().__getitem__(i)
            __annotations__ = {
                "updates": updates,
            }
    
    updates: MetaOapg.properties.updates
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updates"]) -> MetaOapg.properties.updates: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["updates", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updates"]) -> MetaOapg.properties.updates: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["updates", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        updates: typing.Union[MetaOapg.properties.updates, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CatalogUpdatesRequest':
        return super().__new__(
            cls,
            *_args,
            updates=updates,
            _configuration=_configuration,
            **kwargs,
        )

from pygravitino.model.catalog_update_request import CatalogUpdateRequest
