# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pygravitino import schemas  # noqa: F401


class FunctionPartitioning(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "funcName",
            "funcArgs",
            "strategy",
        }
        
        class properties:
            
            
            class strategy(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "function": "FUNCTION",
                    }
                
                @schemas.classproperty
                def FUNCTION(cls):
                    return cls("function")
            funcName = schemas.StrSchema
            
            
            class funcArgs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['FunctionArg']:
                        return FunctionArg
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['FunctionArg'], typing.List['FunctionArg']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'funcArgs':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'FunctionArg':
                    return super().__getitem__(i)
            __annotations__ = {
                "strategy": strategy,
                "funcName": funcName,
                "funcArgs": funcArgs,
            }
    
    funcName: MetaOapg.properties.funcName
    funcArgs: MetaOapg.properties.funcArgs
    strategy: MetaOapg.properties.strategy
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["strategy"]) -> MetaOapg.properties.strategy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["funcName"]) -> MetaOapg.properties.funcName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["funcArgs"]) -> MetaOapg.properties.funcArgs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["strategy", "funcName", "funcArgs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["strategy"]) -> MetaOapg.properties.strategy: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["funcName"]) -> MetaOapg.properties.funcName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["funcArgs"]) -> MetaOapg.properties.funcArgs: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["strategy", "funcName", "funcArgs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        funcName: typing.Union[MetaOapg.properties.funcName, str, ],
        funcArgs: typing.Union[MetaOapg.properties.funcArgs, list, tuple, ],
        strategy: typing.Union[MetaOapg.properties.strategy, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FunctionPartitioning':
        return super().__new__(
            cls,
            *_args,
            funcName=funcName,
            funcArgs=funcArgs,
            strategy=strategy,
            _configuration=_configuration,
            **kwargs,
        )

from pygravitino.model.function_arg import FunctionArg
