# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pygravitino import schemas  # noqa: F401


class ListValue(
    schemas.ListSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The elements of lists partition
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['Literal1']:
            return Literal1

    def __new__(
        cls,
        _arg: typing.Union[typing.Tuple['Literal1'], typing.List['Literal1']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ListValue':
        return super().__new__(
            cls,
            _arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'Literal1':
        return super().__getitem__(i)

from pygravitino.model.literal1 import Literal1
