# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pygravitino import schemas  # noqa: F401


class PartitioningSpec(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        @staticmethod
        def discriminator():
            return {
                'strategy': {
                    'BucketPartitioning': BucketPartitioning,
                    'DayPartitioning': DayPartitioning,
                    'FunctionPartitioning': FunctionPartitioning,
                    'HourPartitioning': HourPartitioning,
                    'IdentityPartitioning': IdentityPartitioning,
                    'ListPartitioning': ListPartitioning,
                    'MonthPartitioning': MonthPartitioning,
                    'RangePartitioning': RangePartitioning,
                    'TruncatePartitioning': TruncatePartitioning,
                    'YearPartitioning': YearPartitioning,
                    'bucket': BucketPartitioning,
                    'day': DayPartitioning,
                    'function': FunctionPartitioning,
                    'hour': HourPartitioning,
                    'identity': IdentityPartitioning,
                    'list': ListPartitioning,
                    'month': MonthPartitioning,
                    'range': RangePartitioning,
                    'truncate': TruncatePartitioning,
                    'year': YearPartitioning,
                }
            }
        
        @classmethod
        @functools.lru_cache()
        def one_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                IdentityPartitioning,
                YearPartitioning,
                MonthPartitioning,
                DayPartitioning,
                HourPartitioning,
                BucketPartitioning,
                TruncatePartitioning,
                ListPartitioning,
                RangePartitioning,
                FunctionPartitioning,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PartitioningSpec':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from pygravitino.model.bucket_partitioning import BucketPartitioning
from pygravitino.model.day_partitioning import DayPartitioning
from pygravitino.model.function_partitioning import FunctionPartitioning
from pygravitino.model.hour_partitioning import HourPartitioning
from pygravitino.model.identity_partitioning import IdentityPartitioning
from pygravitino.model.list_partitioning import ListPartitioning
from pygravitino.model.month_partitioning import MonthPartitioning
from pygravitino.model.range_partitioning import RangePartitioning
from pygravitino.model.truncate_partitioning import TruncatePartitioning
from pygravitino.model.year_partitioning import YearPartitioning
