# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pygravitino import schemas  # noqa: F401


class SortOrder(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "sortTerm",
        }
        
        class properties:
        
            @staticmethod
            def sortTerm() -> typing.Type['FunctionArg']:
                return FunctionArg
            
            
            class direction(
                schemas.EnumBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "asc": "ASC",
                        "desc": "DESC",
                    }
                
                @schemas.classproperty
                def ASC(cls):
                    return cls("asc")
                
                @schemas.classproperty
                def DESC(cls):
                    return cls("desc")
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'direction':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class nullOrdering(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "nulls_first": "FIRST",
                        "nulls_last": "LAST",
                    }
                
                @schemas.classproperty
                def FIRST(cls):
                    return cls("nulls_first")
                
                @schemas.classproperty
                def LAST(cls):
                    return cls("nulls_last")
            __annotations__ = {
                "sortTerm": sortTerm,
                "direction": direction,
                "nullOrdering": nullOrdering,
            }
    
    sortTerm: 'FunctionArg'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sortTerm"]) -> 'FunctionArg': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["direction"]) -> MetaOapg.properties.direction: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nullOrdering"]) -> MetaOapg.properties.nullOrdering: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["sortTerm", "direction", "nullOrdering", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sortTerm"]) -> 'FunctionArg': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["direction"]) -> typing.Union[MetaOapg.properties.direction, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nullOrdering"]) -> typing.Union[MetaOapg.properties.nullOrdering, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["sortTerm", "direction", "nullOrdering", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        sortTerm: 'FunctionArg',
        direction: typing.Union[MetaOapg.properties.direction, None, str, schemas.Unset] = schemas.unset,
        nullOrdering: typing.Union[MetaOapg.properties.nullOrdering, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SortOrder':
        return super().__new__(
            cls,
            *_args,
            sortTerm=sortTerm,
            direction=direction,
            nullOrdering=nullOrdering,
            _configuration=_configuration,
            **kwargs,
        )

from pygravitino.model.function_arg import FunctionArg
