# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pygravitino import schemas  # noqa: F401


class UpdateTableColumnNullabilityRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "fieldName",
            "nullable",
            "@type",
        }
        
        class properties:
            
            
            class type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "updateColumnNullability": "UPDATE_COLUMN_NULLABILITY",
                    }
                
                @schemas.classproperty
                def UPDATE_COLUMN_NULLABILITY(cls):
                    return cls("updateColumnNullability")
        
            @staticmethod
            def fieldName() -> typing.Type['FieldName']:
                return FieldName
            nullable = schemas.BoolSchema
            __annotations__ = {
                "@type": type,
                "fieldName": fieldName,
                "nullable": nullable,
            }
    
    fieldName: 'FieldName'
    nullable: MetaOapg.properties.nullable
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["@type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fieldName"]) -> 'FieldName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nullable"]) -> MetaOapg.properties.nullable: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["@type", "fieldName", "nullable", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["@type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fieldName"]) -> 'FieldName': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nullable"]) -> MetaOapg.properties.nullable: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["@type", "fieldName", "nullable", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        fieldName: 'FieldName',
        nullable: typing.Union[MetaOapg.properties.nullable, bool, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateTableColumnNullabilityRequest':
        return super().__new__(
            cls,
            *_args,
            fieldName=fieldName,
            nullable=nullable,
            _configuration=_configuration,
            **kwargs,
        )

from pygravitino.model.field_name import FieldName
