# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from pygravitino.paths.metalakes_name.put import AlterMetalake
from pygravitino.paths.metalakes.post import CreateMetalake
from pygravitino.paths.metalakes_name.delete import DropMetalake
from pygravitino.paths.metalakes.get import ListMetalakes
from pygravitino.paths.metalakes_name.get import LoadMetalake


class MetalakeApi(
    AlterMetalake,
    CreateMetalake,
    DropMetalake,
    ListMetalakes,
    LoadMetalake,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
