# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from pygravitino.paths.metalaskes_metalake_catalogs_catalog_schemas_schema_tables_table_partitions.post import AddPartitions
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema_tables_table_partitions_partition.get import GetPartition
from pygravitino.paths.metalaskes_metalake_catalogs_catalog_schemas_schema_tables_table_partitions.get import ListPartitions


class PartitionApi(
    AddPartitions,
    GetPartition,
    ListPartitions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
