# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema.put import AlterSchema
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas.post import CreateSchema
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema.delete import DropSchema
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas.get import ListSchemas
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema.get import LoadSchema


class SchemaApi(
    AlterSchema,
    CreateSchema,
    DropSchema,
    ListSchemas,
    LoadSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
