# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema_tables_table.put import AlterTable
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema_tables.post import CreateTable
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema_tables_table.delete import DropTable
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema_tables.get import ListTables
from pygravitino.paths.metalakes_metalake_catalogs_catalog_schemas_schema_tables_table.get import LoadTable


class TableApi(
    AlterTable,
    CreateTable,
    DropTable,
    ListTables,
    LoadTable,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
